// @generated by scripts/sync-site-routes.ts from @repo/site-kit — do not edit.
export { POST } from "@repo/site-kit/app/api/projects/[id]/databases/neon/[neonId]/endpoints/[endpointId]/start/route";
