---
galaxy_info:
  role_name: k3s_server
  author: AlloyDB platform
  description: Install and configure a k3s server (embedded etcd)
  license: Apache-2.0
  min_ansible_version: "2.16"
  platforms:
    - name: Ubuntu
      versions: [jammy, noble]
    - name: Debian
      versions: [bookworm, trixie]
  galaxy_tags: []
dependencies:
  - role: k3s
