// @generated by scripts/sync-site-routes.ts from @repo/site-kit — do not edit.
export {
  DELETE,
  PUT,
} from "@repo/site-kit/app/api/projects/[id]/databases/neon/[neonId]/branches/[branchId]/databases/[db]/data-api/route";
