import {
  AGENT_SCOPES_SUPPORTED,
  buildAgentAuthBlock,
  requestOriginForRequest,
} from "@repo/core/agent-auth/discovery";
import { resolveTenantFromHost } from "@repo/database";

/**
 * auth.md — LLM-readable protocol document for agentic registration.
 * Served per the auth.md open protocol (github.com/workos/auth.md).
 */
export async function GET(request: Request): Promise<Response> {
  const tenant = await resolveTenantFromHost(request.headers.get("host"));
  if (!tenant) return new Response("Unknown tenant host", { status: 404 });
  const site = requestOriginForRequest(request);
  const url = (pathname: string) => new URL(pathname, site).toString();
  const agentAuth = buildAgentAuthBlock(site);

  const lines = [
    "# auth.md",
    "",
    "You are an agent. This service supports **agentic registration**: discover → register → (claim if needed) → exchange for an access_token → call API → handle revocation. Follow the steps in order; do not skip ahead.",
    "",
    `This service is tenant-bound: the API resource is \`${url("/mcp")}\` and the authorization server is \`${site}\`.`,
    "",
    "## Step 1 — Discover",
    "",
    "Protected Resource Metadata:",
    "",
    "```http",
    "GET /.well-known/oauth-protected-resource",
    "```",
    "",
    "Authorization Server metadata (see the `agent_auth` block):",
    "",
    "```http",
    "GET /.well-known/oauth-authorization-server",
    "```",
    "",
    `Supported scopes: \`${AGENT_SCOPES_SUPPORTED.join("`, `")}\`.`,
    "",
    "## Step 2 — Pick a method",
    "",
    `identity_types_supported: ${JSON.stringify(agentAuth.identity_types_supported)}`,
    "",
    "1. **You have a session tied to a user identity and can mint an audience-bound ID-JAG** → `identity_assertion` (if the service lists it and your provider is trusted).",
    "2. **You have only the user's email** → `service_auth`. Claim ceremony required.",
    "3. **You have neither** → `anonymous`. Pre-claim scopes immediately; the user can claim ownership later.",
    "",
    "## Step 3 — Register",
    "",
    "Surface the service name and scope set to the user and confirm before registering (skip for `anonymous`).",
    "",
    "### anonymous",
    "",
    "```http",
    `POST ${agentAuth.identity_endpoint}`,
    "Content-Type: application/json",
    "",
    '{ "type": "anonymous" }',
    "```",
    "",
    "Response: `registration_id`, `identity_assertion` (service-signed JWT), `assertion_expires`, `pre_claim_scopes`, `claim_token`, `claim_url`, `claim_token_expires`, `post_claim_scopes`.",
    "",
    "### service_auth",
    "",
    "```http",
    `POST ${agentAuth.identity_endpoint}`,
    "Content-Type: application/json",
    "",
    '{ "type": "service_auth", "login_hint": "user@example.com" }',
    "```",
    "",
    "Response: `registration_id`, `claim_token`, `claim_url`, and a `claim` block (`user_code`, `verification_uri`, `expires_in`, `interval`). No identity_assertion until the user completes the ceremony.",
    "",
    "### identity_assertion (ID-JAG)",
    "",
    "```http",
    `POST ${agentAuth.identity_endpoint}`,
    "Content-Type: application/json",
    "",
    "{",
    `  "type": "identity_assertion",`,
    `  "assertion_type": "urn:ietf:params:oauth:token-type:id-jag",`,
    `  "assertion": "<your ID-JAG JWT>"`,
    "}",
    "```",
    "",
    "The ID-JAG must carry `aud` = the resource URL, `email_verified: true`, fresh `jti`, near-term `exp`, and `auth_time` within the service's freshness window. A clean match returns an `identity_assertion`; a first-link to an existing account returns `401 interaction_required` with a `claim` block; stale `auth_time` returns `401 login_required`.",
    "",
    "## Step 4 — Claim ceremony (service_auth; optional for anonymous)",
    "",
    "For `anonymous`, start the ceremony:",
    "",
    "```http",
    `POST ${agentAuth.claim_endpoint}`,
    "Content-Type: application/json",
    "",
    '{ "claim_token": "clm_...", "email": "user@example.com" }',
    "```",
    "",
    "Surface to the user in one message:",
    "",
    "> Open this link, sign in, and enter this 6-digit code: **123456**",
    "> <verification_uri>",
    "",
    "The code goes into the page they land on after signing in — not back to you.",
    "",
    "Poll for completion:",
    "",
    "```http",
    `POST ${agentAuth.token_endpoint}`,
    "Content-Type: application/x-www-form-urlencoded",
    "",
    "grant_type=urn:workos:agent-auth:grant-type:claim",
    "&claim_token=<clm_...>",
    `&resource=${url("/mcp")}`,
    "```",
    "",
    '- Pending: `{ "error": "authorization_pending" }` — honor `interval`, back off on `slow_down`.',
    '- Code window expired: `{ "error": "expired_token" }` — re-POST the claim endpoint with the same `claim_token` + `email` for a fresh `user_code`; if it returns `claim_expired`, restart at Step 3.',
    "- Success: standard token response **plus** `identity_assertion` + `assertion_expires`. For anonymous, pre-claim tokens are revoked; use the post-claim access_token.",
    "",
    "## Step 5 — Exchange the assertion",
    "",
    "```http",
    `POST ${agentAuth.token_endpoint}`,
    "Content-Type: application/x-www-form-urlencoded",
    "",
    "grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer",
    "&assertion=<identity_assertion>",
    `&resource=${url("/mcp")}`,
    "```",
    "",
    'Response: `{ access_token, token_type: "Bearer", expires_in, scope }`. There is no refresh_token — re-exchange the same identity_assertion until it expires, then restart at Step 3.',
    "",
    "## Step 6 — Use the access_token",
    "",
    "Send MCP JSON-RPC messages to the resource with the bearer token. The",
    "normal transport is Streamable HTTP; initialize and subsequent",
    "`tools/list` or `tools/call` requests are POSTs.",
    "",
    "```http",
    `POST ${url("/mcp")}`,
    "Authorization: Bearer <access_token>",
    "Content-Type: application/json",
    "Accept: application/json, text/event-stream",
    "MCP-Protocol-Version: 2025-11-25",
    "",
    '{"jsonrpc":"2.0","id":"1","method":"initialize","params":{"protocolVersion":"2025-11-25","capabilities":{},"clientInfo":{"name":"agent","version":"1"}}}',
    "",
    `POST ${url("/mcp")}`,
    "Authorization: Bearer <access_token>",
    "Content-Type: application/json",
    "Accept: application/json, text/event-stream",
    "MCP-Protocol-Version: 2025-11-25",
    "",
    '{"jsonrpc":"2.0","id":"2","method":"tools/list","params":{}}',
    "",
    `POST ${url("/mcp")}`,
    "Authorization: Bearer <access_token>",
    "Content-Type: application/json",
    "Accept: application/json, text/event-stream",
    "MCP-Protocol-Version: 2025-11-25",
    "",
    '{"jsonrpc":"2.0","id":"3","method":"tools/call","params":{"name":"<tool_name>","arguments":{}}}',
    "```",
    "",
    "## Revocation",
    "",
    `- **Credential layer**: POST form-encoded \`token=<access_token>&token_type_hint=access_token\` to \`${agentAuth.revocation_endpoint}\` (RFC 7009; idempotent).`,
    `- **Registration layer**: a trusted provider can POST a Security Event Token (RFC 8417/8935) to \`${agentAuth.events_endpoint}\`; the service invalidates the registration and all derived tokens.`,
    "",
    "## Errors",
    "",
    "| Code | Where | Meaning |",
    "| --- | --- | --- |",
    "| `invalid_request` | /agent/identity | Bad body or unsupported type |",
    "| `anonymous_not_enabled` / `service_auth_not_enabled` / `issuer_not_enabled` | /agent/identity | Method not accepted; pick another |",
    "| `interaction_required` (401) | /agent/identity | Step-up claim required; body carries a `claim` block |",
    "| `login_required` (401) | /agent/identity | `auth_time` too old; re-authenticate at your provider |",
    "| `invalid_claim_token` / `claimed_or_in_flight` / `claim_expired` | claim endpoint | Restart or re-mint the ceremony |",
    "| `invalid_grant` | /oauth2/token | Assertion expired/revoked; restart at Step 3 |",
    "| `unsupported_grant_type` | /oauth2/token | Wrong grant_type |",
    "| `authorization_pending` / `slow_down` / `expired_token` | claim grant | Ceremony polling states |",
    "| `rate_limited` (429) | any | Back off and retry |",
  ];

  return new Response(lines.join("\n"), {
    headers: {
      "Content-Type": "text/markdown; charset=utf-8",
      "Cache-Control": "public, max-age=3600, s-maxage=86400",
    },
  });
}
