// @generated by scripts/sync-site-routes.ts from @repo/site-kit — do not edit.
export { DELETE } from "@repo/site-kit/app/api/account/social/[provider]/route";

export const dynamic = "force-dynamic";
