apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: alloydb
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/snaphq/db-control-panel
  ref:
    branch: main
