// @generated by scripts/sync-site-routes.ts from @repo/site-kit — do not edit.
export { GET } from "@repo/site-kit/app/api/referral/stats/route";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
