import { sql } from 'drizzle-orm';
import {
  type AnyPgColumn,
  bigint,
  boolean,
  check,
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
} from 'drizzle-orm/pg-core';

/**
 * Data model of docs-internal/platform/control-plane.mdx. Ids are prefixed
 * strings generated by the control plane (see crypto/ids.ts) except Neon
 * tenant and timeline ids, which are 32-hex values as Neon requires.
 */

export const ENDPOINT_TYPES = ['read_write', 'read_only'] as const;
export type EndpointType = (typeof ENDPOINT_TYPES)[number];

export const ENDPOINT_STATES = [
  'idle',
  'starting',
  'running',
  'suspending',
] as const;
export type EndpointState = (typeof ENDPOINT_STATES)[number];

export const OPERATION_ACTIONS = [
  'project.create',
  'project.delete',
  'branch.create',
  'branch.delete',
  'endpoint.start',
  'endpoint.suspend',
  'endpoint.update',
  'role.reset_password',
  'database.create',
  'database.delete',
  'data_api.enable',
  'data_api.disable',
  'libsql.create',
  'libsql.delete',
  'libsql.fork',
] as const;
export type OperationAction = (typeof OPERATION_ACTIONS)[number];

export const OPERATION_STATUSES = [
  'scheduling',
  'running',
  'finished',
  'failed',
  'cancelled',
] as const;
export type OperationStatus = (typeof OPERATION_STATUSES)[number];

/** Statuses that hold the per-project mutation lock. */
export const ACTIVE_OPERATION_STATUSES = ['scheduling', 'running'] as const;

const inList = (values: readonly string[]): string =>
  values.map((value) => `'${value}'`).join(', ');

const timestamptz = (name: string) =>
  timestamp(name, { withTimezone: true, mode: 'date' });

export interface BranchSafekeeper {
  id: number;
  hostname: string;
}

/** Placement returned by the storage controller when the timeline is created. */
export interface BranchSafekeepers {
  generation: number;
  safekeepers: BranchSafekeeper[];
}

export interface NodeCapacity {
  /** Free-form per-role capacity numbers; the scheduler defines the keys. */
  [key: string]: unknown;
}

export const neonProject = pgTable(
  'neon_project',
  {
    id: text('id').primaryKey(),
    consoleProjectId: text('console_project_id').notNull(),
    consoleOrgId: text('console_org_id').notNull(),
    name: text('name').notNull(),
    tenantId: text('tenant_id').notNull().unique(),
    pgVersion: integer('pg_version').notNull().default(17),
    historyRetentionSeconds: integer('history_retention_seconds')
      .notNull()
      .default(86_400),
    /** CIDR strings; null means the project does not restrict client IPs. */
    allowedIps: jsonb('allowed_ips').$type<string[]>(),
    createdAt: timestamptz('created_at').notNull().defaultNow(),
    deletedAt: timestamptz('deleted_at'),
  },
  (table) => [
    uniqueIndex('neon_project_console_project_id_live_idx')
      .on(table.consoleProjectId)
      .where(sql`${table.deletedAt} is null`),
    index('neon_project_console_org_id_idx').on(table.consoleOrgId),
  ],
);

export const branch = pgTable(
  'branch',
  {
    id: text('id').primaryKey(),
    projectId: text('project_id')
      .notNull()
      .references(() => neonProject.id),
    name: text('name').notNull(),
    timelineId: text('timeline_id').notNull().unique(),
    parentBranchId: text('parent_branch_id').references(
      (): AnyPgColumn => branch.id,
    ),
    parentLsn: text('parent_lsn'),
    safekeepers: jsonb('safekeepers').$type<BranchSafekeepers>(),
    isDefault: boolean('is_default').notNull().default(false),
    createdAt: timestamptz('created_at').notNull().defaultNow(),
    deletedAt: timestamptz('deleted_at'),
  },
  (table) => [
    uniqueIndex('branch_project_name_live_idx')
      .on(table.projectId, table.name)
      .where(sql`${table.deletedAt} is null`),
    uniqueIndex('branch_project_default_live_idx')
      .on(table.projectId)
      .where(sql`${table.isDefault} and ${table.deletedAt} is null`),
    index('branch_parent_branch_id_idx').on(table.parentBranchId),
  ],
);

export const endpoint = pgTable(
  'endpoint',
  {
    /** `ep-<adjective>-<noun>-<8 base36>`, also the compute id and pod suffix. */
    id: text('id').primaryKey(),
    branchId: text('branch_id')
      .notNull()
      .references(() => branch.id),
    type: text('type').$type<EndpointType>().notNull().default('read_write'),
    /** Compute units: 1 CU is 1 vCPU and 4 GiB. Stored as text, e.g. "0.25". */
    computeSize: text('compute_size').notNull().default('1'),
    /** 0 means never suspend. */
    suspendTimeoutSeconds: integer('suspend_timeout_seconds')
      .notNull()
      .default(300),
    state: text('state').$type<EndpointState>().notNull().default('idle'),
    podName: text('pod_name'),
    podIp: text('pod_ip'),
    lastActiveAt: timestamptz('last_active_at'),
    createdAt: timestamptz('created_at').notNull().defaultNow(),
    deletedAt: timestamptz('deleted_at'),
  },
  (table) => [
    index('endpoint_branch_id_idx').on(table.branchId),
    index('endpoint_state_idx').on(table.state),
    check(
      'endpoint_type_check',
      sql.raw(`type in (${inList(ENDPOINT_TYPES)})`),
    ),
    check(
      'endpoint_state_check',
      sql.raw(`state in (${inList(ENDPOINT_STATES)})`),
    ),
    check(
      'endpoint_suspend_timeout_check',
      sql.raw('suspend_timeout_seconds >= 0'),
    ),
  ],
);

export const role = pgTable(
  'role',
  {
    id: text('id').primaryKey(),
    branchId: text('branch_id')
      .notNull()
      .references(() => branch.id),
    name: text('name').notNull(),
    /** SCRAM-SHA-256 secret; the plaintext password is never stored. */
    scramSecret: text('scram_secret').notNull(),
    createdAt: timestamptz('created_at').notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex('role_branch_name_idx').on(table.branchId, table.name),
  ],
);

export const database = pgTable(
  'database',
  {
    id: text('id').primaryKey(),
    branchId: text('branch_id')
      .notNull()
      .references(() => branch.id),
    name: text('name').notNull(),
    ownerRole: text('owner_role').notNull(),
    dataApiEnabled: boolean('data_api_enabled').notNull().default(false),
    createdAt: timestamptz('created_at').notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex('database_branch_name_idx').on(table.branchId, table.name),
  ],
);

export const node = pgTable('node', {
  /** `ALLOYDB_NODE_ID` from /etc/alloydb/node.env. */
  id: integer('id').primaryKey(),
  name: text('name').notNull(),
  tailscaleIp: text('tailscale_ip').notNull(),
  zone: text('zone').notNull(),
  /** Subset of `pageserver`, `libsql`, `compute`. */
  roles: text('roles').array().notNull().default(sql`'{}'::text[]`),
  capacity: jsonb('capacity').$type<NodeCapacity>().notNull().default({}),
  registeredPageserver: boolean('registered_pageserver')
    .notNull()
    .default(false),
  registeredSafekeepers: boolean('registered_safekeepers')
    .notNull()
    .default(false),
  createdAt: timestamptz('created_at').notNull().defaultNow(),
  updatedAt: timestamptz('updated_at').notNull().defaultNow(),
});

export const libsqlDatabase = pgTable(
  'libsql_database',
  {
    id: text('id').primaryKey(),
    consoleProjectId: text('console_project_id').notNull(),
    name: text('name').notNull(),
    /** sqld namespace, `<db>-<team>`; also the first label of the public host. */
    namespace: text('namespace').notNull(),
    nodeId: integer('node_id')
      .notNull()
      .references(() => node.id),
    state: text('state').notNull().default('creating'),
    sizeLimitBytes: bigint('size_limit_bytes', { mode: 'number' }),
    createdAt: timestamptz('created_at').notNull().defaultNow(),
    deletedAt: timestamptz('deleted_at'),
  },
  (table) => [
    uniqueIndex('libsql_database_namespace_live_idx')
      .on(table.namespace)
      .where(sql`${table.deletedAt} is null`),
    index('libsql_database_console_project_id_idx').on(table.consoleProjectId),
    index('libsql_database_node_id_idx').on(table.nodeId),
  ],
);

/** Free-form progress the runner stores on the operation row. */
export interface OperationProgress {
  /** Names of steps that finished, in order. A retry skips these. */
  completedSteps: string[];
  /** Step outputs later steps read, keyed by step name. */
  outputs: Record<string, unknown>;
}

export const operation = pgTable(
  'operation',
  {
    id: text('id').primaryKey(),
    /**
     * The console's project id from `X-AlloyDB-Project`. It scopes who may read
     * the operation and is the key of the one-active-operation lock.
     */
    consoleProjectId: text('console_project_id').notNull(),
    targetType: text('target_type').notNull(),
    targetId: text('target_id').notNull(),
    action: text('action').$type<OperationAction>().notNull(),
    status: text('status')
      .$type<OperationStatus>()
      .notNull()
      .default('scheduling'),
    failuresCount: integer('failures_count').notNull().default(0),
    error: text('error'),
    /** Request parameters the steps need, written with the desired state. */
    params: jsonb('params')
      .$type<Record<string, unknown>>()
      .notNull()
      .default({}),
    progress: jsonb('progress')
      .$type<OperationProgress>()
      .notNull()
      .default({ completedSteps: [], outputs: {} }),
    createdAt: timestamptz('created_at').notNull().defaultNow(),
    updatedAt: timestamptz('updated_at').notNull().defaultNow(),
    finishedAt: timestamptz('finished_at'),
  },
  (table) => [
    // At most one active operation per project, enforced by the database so
    // concurrent mutations cannot both pass the application-level check.
    uniqueIndex('operation_active_per_project_idx')
      .on(table.consoleProjectId)
      .where(sql`${table.status} in ('scheduling', 'running')`),
    index('operation_target_idx').on(table.targetType, table.targetId),
    check(
      'operation_action_check',
      sql.raw(`action in (${inList(OPERATION_ACTIONS)})`),
    ),
    check(
      'operation_status_check',
      sql.raw(`status in (${inList(OPERATION_STATUSES)})`),
    ),
  ],
);

export const usageEvent = pgTable(
  'usage_event',
  {
    id: text('id').primaryKey(),
    /** `neon_project.id` for Neon usage, the console project id for libSQL usage. */
    projectId: text('project_id').notNull(),
    kind: text('kind').notNull(),
    value: bigint('value', { mode: 'number' }).notNull(),
    idempotencyKey: text('idempotency_key').notNull().unique(),
    recordedAt: timestamptz('recorded_at').notNull().defaultNow(),
  },
  (table) => [
    index('usage_event_project_kind_idx').on(table.projectId, table.kind),
  ],
);
