// @generated by scripts/sync-site-routes.ts from @repo/site-kit — do not edit.
export {
  DELETE,
  GET,
  PATCH,
} from "@repo/site-kit/app/api/account/operators/[id]/route";

export const dynamic = "force-dynamic";
