#!/usr/bin/env bun

/**
 * Generate thin Next.js route shims for every tenant site from the shared
 * route tree in packages/site-kit/src/app.
 *
 * Next.js only discovers routes that exist as files inside an app, so each
 * site keeps one re-export file per shared route. Segment config such as
 * `export const dynamic = "force-dynamic"` must be a literal in the route file
 * itself, so it is copied verbatim instead of re-exported.
 *
 * A site overrides a shared route by committing its own file at the same path
 * without the generated marker; the generator then leaves it alone.
 *
 * Usage:
 *   bun run sites:sync            # write/update/remove shims
 *   bun run sites:sync --check    # fail if any shim is missing or stale
 */

import { spawnSync } from "node:child_process";
import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import path from "node:path";
import { colors } from "./lib/colors";

const ROOT = process.cwd();
const KIT_APP = path.join(ROOT, "packages/site-kit/src/app");
const KIT_IMPORT = "@repo/site-kit/app";
const MARKER =
  "// @generated by scripts/sync-site-routes.ts from @repo/site-kit — do not edit.";

const SPECIAL_FILES = new Set([
  "page",
  "layout",
  "route",
  "loading",
  "error",
  "not-found",
  "template",
  "default",
  "global-error",
  "forbidden",
  "unauthorized",
  "sitemap",
  "robots",
  "manifest",
  "icon",
  "apple-icon",
  "opengraph-image",
  "twitter-image",
]);
const CODE_EXTENSIONS = [".tsx", ".ts", ".jsx", ".js"];
// Next.js reads these statically from the route file, so they cannot be
// re-exported from another module.
const LITERAL_EXPORTS = new Set([
  "dynamic",
  "dynamicParams",
  "revalidate",
  "fetchCache",
  "runtime",
  "preferredRegion",
  "maxDuration",
  "experimental_ppr",
]);

function walk(dir: string): string[] {
  if (!existsSync(dir)) return [];
  return readdirSync(dir).flatMap((entry) => {
    const full = path.join(dir, entry);
    return statSync(full).isDirectory() ? walk(full) : [full];
  });
}

function isSpecialFile(file: string): boolean {
  const ext = path.extname(file);
  return (
    CODE_EXTENSIONS.includes(ext) && SPECIAL_FILES.has(path.basename(file, ext))
  );
}

/** Return the source of the statement starting at `start`, ending at a top-level `;`. */
function statementAt(source: string, start: number): string {
  let depth = 0;
  let quote: string | null = null;
  for (let i = start; i < source.length; i++) {
    const ch = source[i];
    if (quote) {
      if (ch === "\\") i++;
      else if (ch === quote) quote = null;
      continue;
    }
    if (ch === '"' || ch === "'" || ch === "`") quote = ch;
    else if ("([{".includes(ch)) depth++;
    else if (")]}".includes(ch)) depth--;
    else if ((ch === ";" || ch === "\n") && depth === 0) {
      // A newline only ends the statement when the next line starts a new one.
      if (ch === ";") return source.slice(start, i + 1);
      const rest = source.slice(i + 1).trimStart();
      if (!/^[.?:+\-*/|&=]/.test(rest)) return `${source.slice(start, i)};`;
    }
  }
  return source.slice(start);
}

interface ShimSpec {
  useClient: boolean;
  hasDefault: boolean;
  names: string[];
  literals: string[];
}

function analyze(file: string): ShimSpec {
  const source = readFileSync(file, "utf8");
  const spec: ShimSpec = {
    useClient: /^\s*["']use client["']/.test(source),
    hasDefault: /^export default\b/m.test(source),
    names: [],
    literals: [],
  };
  const add = (name: string) => {
    if (name && !spec.names.includes(name)) spec.names.push(name);
  };

  for (const match of source.matchAll(
    /^export\s+(?:async\s+)?(?:function\*?|const|let|var|class)\s+([A-Za-z0-9_$]+)/gm,
  )) {
    const name = match[1];
    if (LITERAL_EXPORTS.has(name)) {
      spec.literals.push(statementAt(source, match.index ?? 0).trim());
    } else add(name);
  }
  for (const match of source.matchAll(
    /^export\s+(type\s+)?\{([^}]*)\}(\s*from\s*["'][^"']+["'])?/gm,
  )) {
    if (match[1]) continue;
    for (const part of match[2].split(",")) {
      const trimmed = part.trim();
      if (!trimmed || trimmed.startsWith("type ")) continue;
      const alias =
        trimmed
          .split(/\s+as\s+/)
          .pop()
          ?.trim() ?? "";
      if (alias === "default") spec.hasDefault = true;
      else if (LITERAL_EXPORTS.has(alias)) {
        throw new Error(
          `${path.relative(ROOT, file)}: segment config "${alias}" must be declared inline, not re-exported`,
        );
      } else add(alias);
    }
  }
  if (/^export\s+\*/m.test(source)) {
    throw new Error(
      `${path.relative(ROOT, file)}: "export *" is not supported in shared routes`,
    );
  }
  return spec;
}

function renderShim(importPath: string, spec: ShimSpec): string {
  const lines: string[] = [];
  if (spec.useClient) lines.push('"use client";', "");
  lines.push(MARKER);
  const exported = [
    ...(spec.hasDefault ? ["default"] : []),
    ...spec.names.sort(),
  ];
  if (exported.length > 0) {
    lines.push(`export { ${exported.join(", ")} } from "${importPath}";`);
  }
  if (spec.literals.length > 0) lines.push("", ...spec.literals);
  return `${lines.join("\n")}\n`;
}

/** Match the committed (biome-formatted) output so `--check` stays stable. */
function formatShim(content: string, target: string): string {
  const needsFormatting = content
    .split("\n")
    .some((line) => line.length > 80 && !line.startsWith("//"));
  if (!needsFormatting) return content;
  const result = spawnSync(
    path.join(ROOT, "node_modules/.bin/biome"),
    ["format", `--stdin-file-path=${target}`],
    { input: content, encoding: "utf8" },
  );
  if (result.status !== 0) {
    throw new Error(`biome failed to format ${target}: ${result.stderr}`);
  }
  return result.stdout;
}

function siteWorkspaces(): string[] {
  return ["apps", "sites"].flatMap((group) => {
    const groupDir = path.join(ROOT, group);
    if (!existsSync(groupDir)) return [];
    return readdirSync(groupDir)
      .map((name) => path.join(groupDir, name))
      .filter((dir) => {
        const manifest = path.join(dir, "package.json");
        if (!existsSync(manifest)) return false;
        const pkg = JSON.parse(readFileSync(manifest, "utf8"));
        return Boolean(pkg.dependencies?.["@repo/site-kit"]);
      });
  });
}

function isGenerated(file: string): boolean {
  return readFileSync(file, "utf8").includes(MARKER);
}

function withoutExtension(file: string): string {
  return file.slice(0, -path.extname(file).length);
}

function findExisting(base: string): string | undefined {
  return CODE_EXTENSIONS.map((ext) => base + ext).find((f) => existsSync(f));
}

function main(): void {
  const check = process.argv.includes("--check");
  const kitRoutes = walk(KIT_APP).filter(isSpecialFile);
  const problems: string[] = [];
  let written = 0;

  for (const site of siteWorkspaces()) {
    const siteApp = path.join(site, "src/app");
    const expected = new Set<string>();

    for (const kitFile of kitRoutes) {
      const rel = path.relative(KIT_APP, kitFile);
      const relBase = withoutExtension(rel);
      const existing = findExisting(path.join(siteApp, relBase));
      if (existing && !isGenerated(existing)) continue; // site override

      const target = existing ?? path.join(siteApp, rel);
      expected.add(target);
      const content = formatShim(
        renderShim(
          `${KIT_IMPORT}/${relBase.split(path.sep).join("/")}`,
          analyze(kitFile),
        ),
        target,
      );
      if (existsSync(target) && readFileSync(target, "utf8") === content) {
        continue;
      }
      if (check) {
        problems.push(`stale or missing shim: ${path.relative(ROOT, target)}`);
        continue;
      }
      mkdirSync(path.dirname(target), { recursive: true });
      writeFileSync(target, content);
      written++;
    }

    for (const file of walk(siteApp).filter(isSpecialFile)) {
      if (expected.has(file) || !isGenerated(file)) continue;
      if (check) {
        problems.push(`orphaned shim: ${path.relative(ROOT, file)}`);
        continue;
      }
      rmSync(file);
      written++;
    }
  }

  if (problems.length > 0) {
    console.error(
      `${colors.red}${colors.bold}Site route shims are out of date:${colors.reset}`,
    );
    for (const problem of problems) console.error(`  ${problem}`);
    console.error("Run `bun run sites:sync` and commit the result.");
    process.exit(1);
  }
  console.log(
    check
      ? "Site route shims are up to date."
      : `Site route shims synced (${written} file(s) changed).`,
  );
}

main();
