// @generated by scripts/sync-site-routes.ts from @repo/site-kit — do not edit.
export { POST } from "@repo/site-kit/app/api/projects/[id]/agents/[slug]/session/route";

export const dynamic = "force-dynamic";
