// @generated by scripts/sync-site-routes.ts from @repo/site-kit — do not edit.
export { POST } from "@repo/site-kit/app/api/account/operators/[id]/tokens/route";

export const dynamic = "force-dynamic";
