// @generated by scripts/sync-site-routes.ts from @repo/site-kit — do not edit.
export { GET } from "@repo/site-kit/app/api/organizations/[slug]/analytics/series/[series]/route";

export const dynamic = "force-dynamic";
