// @generated by scripts/sync-site-routes.ts from @repo/site-kit — do not edit.
export { default } from "@repo/site-kit/app/account/settings/authentication/page";

export const dynamic = "force-dynamic";
